"""Revised models.py

Revision ID: 6ea16949168c
Revises: fad51b8b226c
Create Date: 2025-08-22 09:04:04.473490

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ea16949168c'
down_revision: str | Sequence[str] | None = 'fad51b8b226c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class', 'trainer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class', 'trainer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
