"""final revision

Revision ID: d8f75a1dbf4b
Revises: 6d22b10a08f4
Create Date: 2025-08-25 19:11:39.332674

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8f75a1dbf4b'
down_revision: str | Sequence[str] | None = '6d22b10a08f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('trainer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attendance', 'trainer', ['trainer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'trainer_id')
    # ### end Alembic commands ###
