"""Added activity to member class and updated respective schemas

Revision ID: d9da92570430
Revises: aca7df5cdffc
Create Date: 2025-08-20 08:58:41.850501

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd9da92570430'
down_revision: str | Sequence[str] | None = 'aca7df5cdffc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'active')
    # ### end Alembic commands ###
